from app.adp.routes.base_router import adp
from app.adp.routes.adp_customers import adp_customers
from app.adp.routes.adp_coil_programs import coil_progs
from app.adp.routes.adp_ah_programs import ah_progs
from app.adp.routes.adp_program_parts import prog_parts
from app.adp.routes.adp_program_ratings import prog_ratings
from app.adp.routes.ratings_management import ratings_admin
from app.adp.routes.adp_material_groups import adp_material_groups
from app.adp.routes.adp_material_group_discounts import adp_mat_grp_discs
from app.adp.routes.adp_snps import adp_snps
