from pydantic import BaseModel, Field

class VendorResponse(BaseModel):
    ...
class VendorDetailResponse(BaseModel):
    ...
class VendorQuery(BaseModel):
    ...
class NewVendorResourceObject(BaseModel):
    ...
class NewVendorDetailResourceObject(BaseModel):
    ...
class ExistingVendor(BaseModel):
    ...
class ExistingVendorDetail(BaseModel):
    ...